markdown: redcarpet
highlighter: true
plugins: ./_plugins
paginate: 8

safe: false

#站点基础配置
title: calledT
subTitle: 叫我Kimi，不要叫我唱大猩猩！
description: null
url: /
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: 联系我
    url: http://weibo.com/huanggengtao
    icon: icon-heart
    class: none
  - text: 博客源代码
    url: https://github.com/calledT/calledt.github.io
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: Kimi

#comment config
disqus:
  config: false
  id:

duoshuo:
  config: true
  id: calledt
